services:
  app1:
    image: luxveris/reverse2:app1
    container_name: app1
    restart: unless-stopped
    networks:
      - webnet

  app2:
    image: luxveris/reverse2:app2
    container_name: app2
    restart: unless-stopped
    networks:
      - webnet

  nginx:
    image: luxveris/reverse2:nginx
    container_name: nginx
    ports:  
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
